LeadsStates/Controllers/LocationController.cs
using LeadsStates.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeadsStates.Controllers
{
    [Authorize]
    public class LocationController : Controller
    {
        Repository.Repository repository = new Repository.Repository();
        // GET: Location
        public ActionResult Index()
        {
            LocationVm locationVm = new LocationVm();
            locationVm.Projects = repository.GetProjects();
            locationVm.Cities = repository.GetAllCities();
            return View("AddProject", locationVm);
        }
        public ActionResult AddPhase()
        {
            LocationVm locationVm = new LocationVm();
            locationVm.Cities = repository.GetAllCities();
            locationVm.Projects = repository.GetProjects();
            locationVm.Phase = repository.GetPhases();
            return View(locationVm);
        }
        public ActionResult AddBlock()
        {
            LocationVm locationVm = new LocationVm();
            locationVm.Cities = repository.GetAllCities();
            locationVm.Projects = repository.GetProjects();
            locationVm.Phase = repository.GetPhases();
            locationVm.Blocks = repository.GetBlocks();
            return View(locationVm);
        }
        public bool AddNewProject (int CityId , string ProjectName)
        {
            try
            {
                repository.AddProject(CityId, ProjectName);
                return true;
            }
            catch (Exception ex)
            {

                return false;
            }
        }
        public bool AddNewPhase(int CityId, int ProjectId,string PhaseName)
        {
            try
            {
                repository.AddPhase(CityId, ProjectId, PhaseName);
                return true;
            }
            catch (Exception ex)
            {

                return false;
            }
        }
        public bool AddNewBlock(int CityId, int ProjectId, int PhaseId , string BlockName)
        {
            try
            {
                repository.AddBlocks(CityId, ProjectId, PhaseId , BlockName);
                return true;
            }
            catch (Exception ex)
            {

                return false;
            }
        }
        public bool DeleteProject(int Id)
        {
            try
            {
                repository.DeleteProject(Id);
                return true;
            }
            catch (Exception ex)
            {

                return false;
            }
        }
        public bool DeletePhase(int Id)
        {
            try
            {
                repository.DeletePhase(Id);
                return true;
            }
            catch (Exception ex)
            {

                return false;
            }
        }
        public bool DeleteBlock(int Id)
        {
            try
            {
                repository.DeleteBlock(Id);
                return true;
            }
            catch (Exception ex)
            {

                return false;
            }
        }
    }
}

LeadsStates/Views/Location/AddBlock.cshtml
@model LeadsStates.Models.LocationVm
@{
    ViewBag.Title = "AddBlock";
}

<div class="container-fluid">
    <div class="bg-white rounded shadow p-3 mt-3">
        <div class="row">
            <div class="col-md-8">
                <h2 class="mb-0 text-black font-wight-bold">Add Location Block</h2>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 bg-white rounded shadow p-4 mt-5">
                <form>
                    <div class="row">
                        <div class="col-md-6 mt-2">
                            <label for="" class="d-block">Select City:</label>
                            @Html.DropDownListFor(model => model.SelectedCity, new SelectList(Model.Cities, "Id", "CityName"), new { @class = "form-control", @Id = "CityId" })                            
                        </div>
                        <div class="col-md-6 mt-2">
                            <label for="" class="d-block">Select Location:</label>
                            @Html.DropDownListFor(model => model.SelectedProject, new SelectList(Model.Projects, "Id", "ProjectName"), new { @class = "form-control", @Id = "ProjectId" })
                        </div>
                        <div class="col-md-6 mt-2">
                            <label for="" class="d-block">Select Phase:</label>
                            @Html.DropDownListFor(model => model.SelectedPhase, new SelectList(Model.Phase, "Id", "PhaseName"), new { @class = "form-control", @Id = "PhaseId" })
                        </div>
                        <div class="col-md-6 mt-2">
                            <label for="" class="d-block">Enter Block:</label>
                            <input type="text" class="form-control" id="BlockName" placeholder="block name">
                        </div>
                        @*<div class="col-md-6 mt-2">
                            <div class="form-check pl-0">
                                <label class="d-block" for="defaultCheck1">
                                    IsActive
                                </label>
                                <input type="checkbox" value="" id="defaultCheck1">
                            </div>
                        </div>*@
                        <div class="col-md-12 text-center mt-4">
                            <button class="btn btn-secondary" onclick="addnewBlock()" type="submit">Save</button>
                        </div>
                    </div>
                </form>
                <table class="table mt-5">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">City Name</th>
                            <th scope="col">Location Name</th>
                            <th scope="col">Phases</th>
                            <th scope="col">Block Name</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Blocks)
                        {
                            <tr>
                                <th scope="row">@item.Id</th>
                                <td>@item.CityName</td>
                                <td>@item.ProjectName</td>
                                <td>@item.PhaseName</td>
                                <td>@item.BlockName</td>
                                <td>
                                    <button class="btn btn-danger" type="button" onclick="deleteProject(@item.Id)">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </td>
                            </tr>

                        }
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    function addnewBlock () {
        $.ajax({
                type: "POST", url: '@Url.Action("AddNewBlock", "Location")',
                success: function (data) {

                    window.location.reload();

                },
            data: {
                "CityId": $('#CityId').val(),
                "ProjectId": $('#ProjectId').val(),
                "PhaseId": $('#PhaseId').val(),
                "BlockName": $('#BlockName').val(),


            },
                accept: 'application/json'
            });

    }
    function deleteProject (id) {
       // alert("hello")
        $.ajax({
                type: "POST", url: '@Url.Action("DeleteBlock", "Location")',
                success: function (data) {

                    window.location.reload();

                },
            data: {
                "Id": id

            },
                accept: 'application/json'
            });

    }
</script>

LeadsStates/Views/Location/AddPhase.cshtml
@model LeadsStates.Models.LocationVm
@{
    ViewBag.Title = "AddPhase";
}
<div class="container-fluid">
    <div class="bg-white rounded shadow p-3 mt-3">
        <div class="row">
            <div class="col-md-8">
                <h2 class="mb-0 text-black font-wight-bold">Add Location Block</h2>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 bg-white rounded shadow p-4 mt-5">
                <form>
                    <div class="row">
                        <div class="col-md-6 mt-2">
                            <label for="" class="d-block">Select City:</label>
                            @Html.DropDownListFor(model => model.SelectedCity, new SelectList(Model.Cities, "Id", "CityName"), new { @class = "form-control", @Id = "CityId" })
                        </div>
                        <div class="col-md-6 mt-2">
                            <label for="" class="d-block">Select Location:</label>
                            @Html.DropDownListFor(model => model.SelectedProject, new SelectList(Model.Projects, "Id", "ProjectName"), new { @class = "form-control", @Id = "ProjectId" })
                        </div>                        
                        <div class="col-md-6 mt-2">
                            <label for="" class="d-block">Enter Phase:</label>
                            <input type="text" class="form-control" id="PhaseName" placeholder="Phase name">
                        </div>                        
                        <div class="col-md-12 text-center mt-4">
                            <button class="btn btn-secondary" type="submit" onclick="addnewPhase()">Save</button>
                        </div>
                    </div>
                </form>
                <table class="table mt-5">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">City Name</th>
                            <th scope="col">Location Name</th>
                            <th scope="col">Phase Name</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                            @foreach (var item in Model.Phase)
                            {
                            <tr>
                                <th scope="row">@item.Id</th>
                                <td>@item.CityName</td>
                                <td>@item.ProjectName</td>
                                <td>@item.PhaseName</td>
                                <td>
                                    <button class="btn btn-danger" type="button" onclick="deleteProject(@item.Id)">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </td>
                            </tr>

                        }
                           
                        </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    function addnewPhase () {
       // alert("hello")
        $.ajax({
                type: "POST", url: '@Url.Action("AddNewPhase", "Location")',
                success: function (data) {

                    window.location.reload();

                },
            data: {
                "CityId": $('#CityId').val(),
                "ProjectId": $('#ProjectId').val(),
                "PhaseName": $('#PhaseName').val()

            },
                accept: 'application/json'
            });

    }
    function deleteProject (id) {
       // alert("hello")
        $.ajax({
                type: "POST", url: '@Url.Action("DeletePhase", "Location")',
                success: function (data) {

                    window.location.reload();

                },
            data: {
                "Id": id

            },
                accept: 'application/json'
            });

    }
</script>

LeadsStates/Views/Location/AddProject.cshtml
@model LeadsStates.Models.LocationVm 
@{
    ViewBag.Title = "AddProject";
}

<div class="container-fluid">
    <div class="bg-white rounded shadow p-3 mt-3">
        <div class="row">
            <div class="col-md-8">
                <h2 class="mb-0 text-black font-wight-bold">Add Location</h2>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 bg-white rounded shadow p-4 mt-5">
                <form>
                    <div class="row">
                        <div class="col-md-6 mt-2">
                            <label for="" class="d-block">Select City:</label>
                            @Html.DropDownListFor(model => model.SelectedCity, new SelectList(Model.Cities, "Id", "CityName"), new { @class = "form-control", @Id = "CityId" })
                        </div>                        
                        <div class="col-md-6 mt-2">
                            <label for="" class="d-block">Enter Project Name:</label>
                            <input type="text" id="ProjectName" class="form-control" placeholder="Project name">
                        </div>
                      
                        <div class="col-md-12 text-center mt-4">
                            <button class="btn btn-secondary" type="submit" onclick="addnewTask()">Save</button>
                        </div>
                    </div>
                </form>
                <table class="table mt-5">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">City Name</th>
                            <th scope="col">Location Name</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Projects)
                        {
                            <tr>
                                <th scope="row">@item.Id</th>
                                <td>@item.CityName</td>
                                <td>@item.ProjectName</td>
                              <td>
                                    <button class="btn btn-danger" type="button" onclick="deleteProject(@item.Id)">
                                        <i class="fas fa-trash"></i>
                                    </button>
                              </td>
                            </tr>

                        }
                       
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    function addnewTask () {
       // alert("hello")
        $.ajax({
                type: "POST", url: '@Url.Action("AddNewProject", "Location")',
                success: function (data) {

                    window.location.reload();

                },
            data: {
                "CityId": $('#CityId').val(),
                "ProjectName": $('#ProjectName').val()

            },
                accept: 'application/json'
            });

    }
    function deleteProject (id) {
       // alert("hello")
        $.ajax({
                type: "POST", url: '@Url.Action("DeleteProject", "Location")',
                success: function (data) {

                    window.location.reload();

                },
            data: {
                "Id": id              

            },
                accept: 'application/json'
            });

    }
</script>